#!/bin/sh

# Env vars of APPRIS web server
#source ${PWD}/../../conf/apprisrc
#source ${PWD}/../../conf/apprisrc.WS
. ${PWD}/../../conf/apprisrc
. ${PWD}/../../conf/apprisrc.WS

# Then, go!
exec perl "${0}.pl" "$@"

