[PATHS]
home=APPRIS__HOME/code/src/firestar/source
lib=APPRIS__HOME/code/src/firestar/source/lib
faatmp=APPRIS__CACHE__WORKSPACE
chads=APPRIS__HOME/db/firestar
[MYSQL]
dbHost=localhost
dbName=FireDB
user=firedb
pass=h2AZaX6iTYkc
[DATABASES]
release=16Nov2020
nrdb=sprot_clean_trembl_clean_70
hhbdb=hhblits_
hhprof=nr20_12Aug11
blast_path=APPRIS__HOME/db/firestar
hhdb_path=APPRIS__HOME/db/firestar
[PROGRAMS]
square=APPRIS__HOME/code/src/firestar/source/Square/another_fire_mess_web
square_test=APPRIS__HOME/code/src/firestar/source/Square/another_fire_mess_test
bstbin=APPRIS__HOME/code/opt/blast-2.2.26/bin
hhblits=APPRIS__HOME/code/opt/hhsuite-2.0.16-linux-x86_64/bin/hhblits
[EXT_LINKS]
PubChem=http://pubchem.ncbi.nlm.nih.gov/summary/summary.cgi?cid=
KEGG COMPOUND=http://www.genome.jp/dbget-bin/www_bget?cpd:
KEGG DRUG=http://www.kegg.jp/dbget-bin/www_bget?dr:
ChEMBL=https://www.ebi.ac.uk/chembldb/compound/inspect/
ChEBI=http://www.ebi.ac.uk/chebi/advancedSearchFT.do?searchString=
DrugBank=http://www.drugbank.ca/drugs/
MetaCyc=http://metacyc.org/META/NEW-IMAGE?type=NIL&object=
PDB_page=http://www.pdb.org/pdb/ligand/ligandsummary.do?hetId=
PDB_image=http://www.pdb.org/pdb/images/
DB_fetch=http://www.ebi.ac.uk/Tools/dbfetch/dbfetch?db=UniProtKB&id=
