/*
  File autogenerated by gengetopt version 2.12.2
  generated with the following command:
  /home/ae/hakanv/gengetopt/bin/gengetopt --file-name=cmdline_hmmsearch 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline_hmmsearch.h"

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->hmmnamefile_given = 0 ;
  args_info->seqnamefile_given = 0 ;
  args_info->seqformat_given = 0 ;
  args_info->outpath_given = 0 ;
  args_info->freqfile_given = 0 ;
  args_info->smxfile_given = 0 ;
  args_info->replfile_given = 0 ;
  args_info->priorfile_given = 0 ;
  args_info->nullfile_given = 0 ;
  args_info->anchor_given = 0 ;
  args_info->labeloutput_given = 0 ;
  args_info->alignmentoutput_given = 0 ;
  args_info->msascoring_given = 0 ;
  args_info->usecolumns_given = 0 ;
  args_info->nolabels_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->viterbi_given = 0 ;
  args_info->nbest_given = 0 ;
  args_info->forward_given = 0 ;
  args_info->max_d_given = 0 ;
  args_info->path_given = 0 ;
  args_info->nopostout_given = 0 ;
  args_info->nolabelout_given = 0 ;
  args_info->nollout_given = 0 ;
  args_info->nooddsout_given = 0 ;
  args_info->norevout_given = 0 ;
  args_info->alignpostout_given = 0 ;
  args_info->alignlabelout_given = 0 ;
  args_info->labelllout_given = 0 ;
  args_info->labeloddsout_given = 0 ;
  args_info->labelrevout_given = 0 ;
  args_info->score_algs_group_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->hmmnamefile_arg = NULL;
  args_info->seqnamefile_arg = NULL;
  args_info->seqformat_arg = NULL;
  args_info->outpath_arg = NULL;
  args_info->freqfile_arg = NULL;
  args_info->smxfile_arg = NULL;
  args_info->replfile_arg = NULL;
  args_info->priorfile_arg = NULL;
  args_info->nullfile_arg = NULL;
  args_info->anchor_arg = NULL;
  args_info->labeloutput_flag = 0;
  args_info->alignmentoutput_flag = 0;
  args_info->msascoring_arg = NULL;
  args_info->usecolumns_arg = NULL;
  args_info->nolabels_flag = 0;
  args_info->verbose_flag = 0;
  args_info->max_d_flag = 0;
  args_info->path_flag = 0;
  args_info->nopostout_flag = 0;
  args_info->nolabelout_flag = 0;
  args_info->nollout_flag = 0;
  args_info->nooddsout_flag = 0;
  args_info->norevout_flag = 0;
  args_info->alignpostout_flag = 0;
  args_info->alignlabelout_flag = 0;
  args_info->labelllout_flag = 0;
  args_info->labeloddsout_flag = 0;
  args_info->labelrevout_flag = 0;
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n"
  "Purpose:\n"
"  score sequences on hidden markov models\n"
  "\n"
  "Usage: %s [OPTIONS]...\n", CMDLINE_PARSER_PACKAGE);
  printf("\n");
  printf("%s\n","  -h, --help                  Print help and exit");
  printf("%s\n","  -V, --version               Print version and exit");
  printf("%s\n","  -m, --hmmnamefile=filename  model namefile for models in hmg format");
  printf("%s\n","  -s, --seqnamefile=filename  sequence namefile (for seuences in fasta, smod, \n                                msamod or prfmod format)");
  printf("%s\n","  -f, --seqformat=STRING      format of input sequences (fa=fasta, s=smod, \n                                msa=msamod, prf=prfmod)");
  printf("%s\n","  -o, --outpath=dir           output directory");
  printf("%s\n","  -q, --freqfile=filename     background frequency file");
  printf("%s\n","  -x, --smxfile=filename      substitution matrix file");
  printf("%s\n","  -r, --replfile=filename     replacement letter file");
  printf("%s\n","  -p, --priorfile=filename    sequence prior file (for msa input files)");
  printf("%s\n","  -n, --nullfile=filename     null model file");
  printf("%s\n","  -a, --anchor=STRING         hmm=results are hmm-ancored (default), \n                                seq=results are sequence anchored");
  printf("%s\n","  -L, --labeloutput           output will print predicted labeling and \n                                posterior label probabilities  (default=off)");
  printf("%s\n","  -A, --alignmentoutput       output will print log likelihood, log odds and \n                                reversi scores  (default=off)");
  printf("%s\n","  -M, --msascoring=STRING     scoring method for alignment and profile data \n                                options = DP/DPPI/GM/GMR/DPPI/PI/PIS default=GM");
  printf("%s\n","  -c, --usecolumns=STRING     specify which columns to use for alignment input \n                                data, options = all/nr, where all means use all \n                                columns\n                                and nr specifies a sequence in the alignment \n                                and the columns where this sequence have \n                                non-gap symbls are used\n                                default = all");
  printf("%s\n","      --nolabels              do not use labels even though the input sequences \n                                are labeled  (default=off)");
  printf("%s\n","  -v, --verbose               print some information about what is going on  \n                                (default=off)");
  printf("%s\n","\n Group: score_algs");
  printf("%s\n","      --viterbi               Use viterbi algorithm for alignment and/or label \n                                scoring (default no)");
  printf("%s\n","      --nbest                 Use n-best (=1-best) algorithm for label scoring \n                                (default yes)");
  printf("%s\n","      --forward               Use forward algorithm for alignment scoring \n                                (default yes)");
  printf("%s\n","      --max_d                 Retrain model on each sequence using Baum-Welch \n                                before scoring  (default=off)");
  printf("%s\n","\noptions for specific output control:");
  printf("%s\n","      --path                  Print most likely statepath  (default=off)");
  printf("%s\n","      --nopostout             no posterior probability information for label \n                                scoring  (default=off)");
  printf("%s\n","      --nolabelout            no predicted labeling for label scoring  \n                                (default=off)");
  printf("%s\n","      --nollout               no log likelihood score for alignment scoring  \n                                (default=off)");
  printf("%s\n","      --nooddsout             no log odds score for alignment scoring  \n                                (default=off)");
  printf("%s\n","      --norevout              no reversi score for alignment scoring  \n                                (default=off)");
  printf("%s\n","      --alignpostout          print posterior probability information for \n                                alignment scoring  (default=off)");
  printf("%s\n","      --alignlabelout         print predicted labeling for alignment scoring  \n                                (default=off)");
  printf("%s\n","      --labelllout            print log likelihood score for label scoring  \n                                (default=off)");
  printf("%s\n","      --labeloddsout          print log odds score for label scoring  \n                                (default=off)");
  printf("%s\n","      --labelrevout           print reversi score for label scoring  \n                                (default=off)");
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  
  if (args_info->hmmnamefile_arg)
    {
      free (args_info->hmmnamefile_arg); /* free previous argument */
      args_info->hmmnamefile_arg = 0;
    }
  if (args_info->seqnamefile_arg)
    {
      free (args_info->seqnamefile_arg); /* free previous argument */
      args_info->seqnamefile_arg = 0;
    }
  if (args_info->seqformat_arg)
    {
      free (args_info->seqformat_arg); /* free previous argument */
      args_info->seqformat_arg = 0;
    }
  if (args_info->outpath_arg)
    {
      free (args_info->outpath_arg); /* free previous argument */
      args_info->outpath_arg = 0;
    }
  if (args_info->freqfile_arg)
    {
      free (args_info->freqfile_arg); /* free previous argument */
      args_info->freqfile_arg = 0;
    }
  if (args_info->smxfile_arg)
    {
      free (args_info->smxfile_arg); /* free previous argument */
      args_info->smxfile_arg = 0;
    }
  if (args_info->replfile_arg)
    {
      free (args_info->replfile_arg); /* free previous argument */
      args_info->replfile_arg = 0;
    }
  if (args_info->priorfile_arg)
    {
      free (args_info->priorfile_arg); /* free previous argument */
      args_info->priorfile_arg = 0;
    }
  if (args_info->nullfile_arg)
    {
      free (args_info->nullfile_arg); /* free previous argument */
      args_info->nullfile_arg = 0;
    }
  if (args_info->anchor_arg)
    {
      free (args_info->anchor_arg); /* free previous argument */
      args_info->anchor_arg = 0;
    }
  if (args_info->msascoring_arg)
    {
      free (args_info->msascoring_arg); /* free previous argument */
      args_info->msascoring_arg = 0;
    }
  if (args_info->usecolumns_arg)
    {
      free (args_info->usecolumns_arg); /* free previous argument */
      args_info->usecolumns_arg = 0;
    }
  
  clear_given (args_info);
}

/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static void
reset_group_score_algs(struct gengetopt_args_info *args_info);

static void
reset_group_score_algs(struct gengetopt_args_info *args_info)
{
  if (! args_info->score_algs_group_counter)
    return;
  
  args_info->viterbi_given = 0 ;
  args_info->nbest_given = 0 ;
  args_info->forward_given = 0 ;

  args_info->score_algs_group_counter = 0;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "hmmnamefile",	1, NULL, 'm' },
        { "seqnamefile",	1, NULL, 's' },
        { "seqformat",	1, NULL, 'f' },
        { "outpath",	1, NULL, 'o' },
        { "freqfile",	1, NULL, 'q' },
        { "smxfile",	1, NULL, 'x' },
        { "replfile",	1, NULL, 'r' },
        { "priorfile",	1, NULL, 'p' },
        { "nullfile",	1, NULL, 'n' },
        { "anchor",	1, NULL, 'a' },
        { "labeloutput",	0, NULL, 'L' },
        { "alignmentoutput",	0, NULL, 'A' },
        { "msascoring",	1, NULL, 'M' },
        { "usecolumns",	1, NULL, 'c' },
        { "nolabels",	0, NULL, 0 },
        { "verbose",	0, NULL, 'v' },
        { "viterbi",	0, NULL, 0 },
        { "nbest",	0, NULL, 0 },
        { "forward",	0, NULL, 0 },
        { "max_d",	0, NULL, 0 },
        { "path",	0, NULL, 0 },
        { "nopostout",	0, NULL, 0 },
        { "nolabelout",	0, NULL, 0 },
        { "nollout",	0, NULL, 0 },
        { "nooddsout",	0, NULL, 0 },
        { "norevout",	0, NULL, 0 },
        { "alignpostout",	0, NULL, 0 },
        { "alignlabelout",	0, NULL, 0 },
        { "labelllout",	0, NULL, 0 },
        { "labeloddsout",	0, NULL, 0 },
        { "labelrevout",	0, NULL, 0 },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVm:s:f:o:q:x:r:p:n:a:LAM:c:v", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          exit (EXIT_SUCCESS);

        case 'm':	/* model namefile for models in hmg format.  */
          if (local_args_info.hmmnamefile_given)
            {
              fprintf (stderr, "%s: `--hmmnamefile' (`-m') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->hmmnamefile_given && ! override)
            continue;
          local_args_info.hmmnamefile_given = 1;
          args_info->hmmnamefile_given = 1;
          if (args_info->hmmnamefile_arg)
            free (args_info->hmmnamefile_arg); /* free previous string */
          args_info->hmmnamefile_arg = gengetopt_strdup (optarg);
          break;

        case 's':	/* sequence namefile (for seuences in fasta, smod, msamod or prfmod format).  */
          if (local_args_info.seqnamefile_given)
            {
              fprintf (stderr, "%s: `--seqnamefile' (`-s') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->seqnamefile_given && ! override)
            continue;
          local_args_info.seqnamefile_given = 1;
          args_info->seqnamefile_given = 1;
          if (args_info->seqnamefile_arg)
            free (args_info->seqnamefile_arg); /* free previous string */
          args_info->seqnamefile_arg = gengetopt_strdup (optarg);
          break;

        case 'f':	/* format of input sequences (fa=fasta, s=smod, msa=msamod, prf=prfmod).  */
          if (local_args_info.seqformat_given)
            {
              fprintf (stderr, "%s: `--seqformat' (`-f') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->seqformat_given && ! override)
            continue;
          local_args_info.seqformat_given = 1;
          args_info->seqformat_given = 1;
          if (args_info->seqformat_arg)
            free (args_info->seqformat_arg); /* free previous string */
          args_info->seqformat_arg = gengetopt_strdup (optarg);
          break;

        case 'o':	/* output directory.  */
          if (local_args_info.outpath_given)
            {
              fprintf (stderr, "%s: `--outpath' (`-o') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->outpath_given && ! override)
            continue;
          local_args_info.outpath_given = 1;
          args_info->outpath_given = 1;
          if (args_info->outpath_arg)
            free (args_info->outpath_arg); /* free previous string */
          args_info->outpath_arg = gengetopt_strdup (optarg);
          break;

        case 'q':	/* background frequency file.  */
          if (local_args_info.freqfile_given)
            {
              fprintf (stderr, "%s: `--freqfile' (`-q') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->freqfile_given && ! override)
            continue;
          local_args_info.freqfile_given = 1;
          args_info->freqfile_given = 1;
          if (args_info->freqfile_arg)
            free (args_info->freqfile_arg); /* free previous string */
          args_info->freqfile_arg = gengetopt_strdup (optarg);
          break;

        case 'x':	/* substitution matrix file.  */
          if (local_args_info.smxfile_given)
            {
              fprintf (stderr, "%s: `--smxfile' (`-x') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->smxfile_given && ! override)
            continue;
          local_args_info.smxfile_given = 1;
          args_info->smxfile_given = 1;
          if (args_info->smxfile_arg)
            free (args_info->smxfile_arg); /* free previous string */
          args_info->smxfile_arg = gengetopt_strdup (optarg);
          break;

        case 'r':	/* replacement letter file.  */
          if (local_args_info.replfile_given)
            {
              fprintf (stderr, "%s: `--replfile' (`-r') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->replfile_given && ! override)
            continue;
          local_args_info.replfile_given = 1;
          args_info->replfile_given = 1;
          if (args_info->replfile_arg)
            free (args_info->replfile_arg); /* free previous string */
          args_info->replfile_arg = gengetopt_strdup (optarg);
          break;

        case 'p':	/* sequence prior file (for msa input files).  */
          if (local_args_info.priorfile_given)
            {
              fprintf (stderr, "%s: `--priorfile' (`-p') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->priorfile_given && ! override)
            continue;
          local_args_info.priorfile_given = 1;
          args_info->priorfile_given = 1;
          if (args_info->priorfile_arg)
            free (args_info->priorfile_arg); /* free previous string */
          args_info->priorfile_arg = gengetopt_strdup (optarg);
          break;

        case 'n':	/* null model file.  */
          if (local_args_info.nullfile_given)
            {
              fprintf (stderr, "%s: `--nullfile' (`-n') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->nullfile_given && ! override)
            continue;
          local_args_info.nullfile_given = 1;
          args_info->nullfile_given = 1;
          if (args_info->nullfile_arg)
            free (args_info->nullfile_arg); /* free previous string */
          args_info->nullfile_arg = gengetopt_strdup (optarg);
          break;

        case 'a':	/* hmm=results are hmm-ancored (default), seq=results are sequence anchored.  */
          if (local_args_info.anchor_given)
            {
              fprintf (stderr, "%s: `--anchor' (`-a') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->anchor_given && ! override)
            continue;
          local_args_info.anchor_given = 1;
          args_info->anchor_given = 1;
          if (args_info->anchor_arg)
            free (args_info->anchor_arg); /* free previous string */
          args_info->anchor_arg = gengetopt_strdup (optarg);
          break;

        case 'L':	/* output will print predicted labeling and posterior label probabilities.  */
          if (local_args_info.labeloutput_given)
            {
              fprintf (stderr, "%s: `--labeloutput' (`-L') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->labeloutput_given && ! override)
            continue;
          local_args_info.labeloutput_given = 1;
          args_info->labeloutput_given = 1;
          args_info->labeloutput_flag = !(args_info->labeloutput_flag);
          break;

        case 'A':	/* output will print log likelihood, log odds and reversi scores.  */
          if (local_args_info.alignmentoutput_given)
            {
              fprintf (stderr, "%s: `--alignmentoutput' (`-A') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->alignmentoutput_given && ! override)
            continue;
          local_args_info.alignmentoutput_given = 1;
          args_info->alignmentoutput_given = 1;
          args_info->alignmentoutput_flag = !(args_info->alignmentoutput_flag);
          break;

        case 'M':	/* scoring method for alignment and profile data options = DP/DPPI/GM/GMR/DPPI/PI/PIS default=GM.  */
          if (local_args_info.msascoring_given)
            {
              fprintf (stderr, "%s: `--msascoring' (`-M') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->msascoring_given && ! override)
            continue;
          local_args_info.msascoring_given = 1;
          args_info->msascoring_given = 1;
          if (args_info->msascoring_arg)
            free (args_info->msascoring_arg); /* free previous string */
          args_info->msascoring_arg = gengetopt_strdup (optarg);
          break;

        case 'c':	/* specify which columns to use for alignment input data, options = all/nr, where all means use all columns
        and nr specifies a sequence in the alignment and the columns where this sequence have non-gap symbls are used
        default = all.  */
          if (local_args_info.usecolumns_given)
            {
              fprintf (stderr, "%s: `--usecolumns' (`-c') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->usecolumns_given && ! override)
            continue;
          local_args_info.usecolumns_given = 1;
          args_info->usecolumns_given = 1;
          if (args_info->usecolumns_arg)
            free (args_info->usecolumns_arg); /* free previous string */
          args_info->usecolumns_arg = gengetopt_strdup (optarg);
          break;

        case 'v':	/* print some information about what is going on.  */
          if (local_args_info.verbose_given)
            {
              fprintf (stderr, "%s: `--verbose' (`-v') option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->verbose_given && ! override)
            continue;
          local_args_info.verbose_given = 1;
          args_info->verbose_given = 1;
          args_info->verbose_flag = !(args_info->verbose_flag);
          break;


        case 0:	/* Long option with no short option */
          /* do not use labels even though the input sequences are labeled.  */
          if (strcmp (long_options[option_index].name, "nolabels") == 0)
          {
            if (local_args_info.nolabels_given)
              {
                fprintf (stderr, "%s: `--nolabels' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->nolabels_given && ! override)
              continue;
            local_args_info.nolabels_given = 1;
            args_info->nolabels_given = 1;
            args_info->nolabels_flag = !(args_info->nolabels_flag);
          }
          
          /* Use viterbi algorithm for alignment and/or label scoring (default no).  */
          else if (strcmp (long_options[option_index].name, "viterbi") == 0)
          {
            if (local_args_info.viterbi_given)
              {
                fprintf (stderr, "%s: `--viterbi' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->viterbi_given && ! override)
              continue;
            local_args_info.viterbi_given = 1;
            args_info->viterbi_given = 1;
            if (args_info->score_algs_group_counter && override)
              reset_group_score_algs (args_info);
            args_info->score_algs_group_counter += 1;
            
            break;
          }
          
          /* Use n-best (=1-best) algorithm for label scoring (default yes).  */
          else if (strcmp (long_options[option_index].name, "nbest") == 0)
          {
            if (local_args_info.nbest_given)
              {
                fprintf (stderr, "%s: `--nbest' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->nbest_given && ! override)
              continue;
            local_args_info.nbest_given = 1;
            args_info->nbest_given = 1;
            if (args_info->score_algs_group_counter && override)
              reset_group_score_algs (args_info);
            args_info->score_algs_group_counter += 1;
            
            break;
          }
          
          /* Use forward algorithm for alignment scoring (default yes).  */
          else if (strcmp (long_options[option_index].name, "forward") == 0)
          {
            if (local_args_info.forward_given)
              {
                fprintf (stderr, "%s: `--forward' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->forward_given && ! override)
              continue;
            local_args_info.forward_given = 1;
            args_info->forward_given = 1;
            if (args_info->score_algs_group_counter && override)
              reset_group_score_algs (args_info);
            args_info->score_algs_group_counter += 1;
            
            break;
          }
          
          /* Retrain model on each sequence using Baum-Welch before scoring.  */
          else if (strcmp (long_options[option_index].name, "max_d") == 0)
          {
            if (local_args_info.max_d_given)
              {
                fprintf (stderr, "%s: `--max_d' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->max_d_given && ! override)
              continue;
            local_args_info.max_d_given = 1;
            args_info->max_d_given = 1;
            args_info->max_d_flag = !(args_info->max_d_flag);
          }
          
          /* Print most likely statepath.  */
          else if (strcmp (long_options[option_index].name, "path") == 0)
          {
            if (local_args_info.path_given)
              {
                fprintf (stderr, "%s: `--path' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->path_given && ! override)
              continue;
            local_args_info.path_given = 1;
            args_info->path_given = 1;
            args_info->path_flag = !(args_info->path_flag);
          }
          
          /* no posterior probability information for label scoring.  */
          else if (strcmp (long_options[option_index].name, "nopostout") == 0)
          {
            if (local_args_info.nopostout_given)
              {
                fprintf (stderr, "%s: `--nopostout' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->nopostout_given && ! override)
              continue;
            local_args_info.nopostout_given = 1;
            args_info->nopostout_given = 1;
            args_info->nopostout_flag = !(args_info->nopostout_flag);
          }
          
          /* no predicted labeling for label scoring.  */
          else if (strcmp (long_options[option_index].name, "nolabelout") == 0)
          {
            if (local_args_info.nolabelout_given)
              {
                fprintf (stderr, "%s: `--nolabelout' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->nolabelout_given && ! override)
              continue;
            local_args_info.nolabelout_given = 1;
            args_info->nolabelout_given = 1;
            args_info->nolabelout_flag = !(args_info->nolabelout_flag);
          }
          
          /* no log likelihood score for alignment scoring.  */
          else if (strcmp (long_options[option_index].name, "nollout") == 0)
          {
            if (local_args_info.nollout_given)
              {
                fprintf (stderr, "%s: `--nollout' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->nollout_given && ! override)
              continue;
            local_args_info.nollout_given = 1;
            args_info->nollout_given = 1;
            args_info->nollout_flag = !(args_info->nollout_flag);
          }
          
          /* no log odds score for alignment scoring.  */
          else if (strcmp (long_options[option_index].name, "nooddsout") == 0)
          {
            if (local_args_info.nooddsout_given)
              {
                fprintf (stderr, "%s: `--nooddsout' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->nooddsout_given && ! override)
              continue;
            local_args_info.nooddsout_given = 1;
            args_info->nooddsout_given = 1;
            args_info->nooddsout_flag = !(args_info->nooddsout_flag);
          }
          
          /* no reversi score for alignment scoring.  */
          else if (strcmp (long_options[option_index].name, "norevout") == 0)
          {
            if (local_args_info.norevout_given)
              {
                fprintf (stderr, "%s: `--norevout' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->norevout_given && ! override)
              continue;
            local_args_info.norevout_given = 1;
            args_info->norevout_given = 1;
            args_info->norevout_flag = !(args_info->norevout_flag);
          }
          
          /* print posterior probability information for alignment scoring.  */
          else if (strcmp (long_options[option_index].name, "alignpostout") == 0)
          {
            if (local_args_info.alignpostout_given)
              {
                fprintf (stderr, "%s: `--alignpostout' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->alignpostout_given && ! override)
              continue;
            local_args_info.alignpostout_given = 1;
            args_info->alignpostout_given = 1;
            args_info->alignpostout_flag = !(args_info->alignpostout_flag);
          }
          
          /* print predicted labeling for alignment scoring.  */
          else if (strcmp (long_options[option_index].name, "alignlabelout") == 0)
          {
            if (local_args_info.alignlabelout_given)
              {
                fprintf (stderr, "%s: `--alignlabelout' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->alignlabelout_given && ! override)
              continue;
            local_args_info.alignlabelout_given = 1;
            args_info->alignlabelout_given = 1;
            args_info->alignlabelout_flag = !(args_info->alignlabelout_flag);
          }
          
          /* print log likelihood score for label scoring.  */
          else if (strcmp (long_options[option_index].name, "labelllout") == 0)
          {
            if (local_args_info.labelllout_given)
              {
                fprintf (stderr, "%s: `--labelllout' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->labelllout_given && ! override)
              continue;
            local_args_info.labelllout_given = 1;
            args_info->labelllout_given = 1;
            args_info->labelllout_flag = !(args_info->labelllout_flag);
          }
          
          /* print log odds score for label scoring.  */
          else if (strcmp (long_options[option_index].name, "labeloddsout") == 0)
          {
            if (local_args_info.labeloddsout_given)
              {
                fprintf (stderr, "%s: `--labeloddsout' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->labeloddsout_given && ! override)
              continue;
            local_args_info.labeloddsout_given = 1;
            args_info->labeloddsout_given = 1;
            args_info->labeloddsout_flag = !(args_info->labeloddsout_flag);
          }
          
          /* print reversi score for label scoring.  */
          else if (strcmp (long_options[option_index].name, "labelrevout") == 0)
          {
            if (local_args_info.labelrevout_given)
              {
                fprintf (stderr, "%s: `--labelrevout' option given more than once%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->labelrevout_given && ! override)
              continue;
            local_args_info.labelrevout_given = 1;
            args_info->labelrevout_given = 1;
            args_info->labelrevout_flag = !(args_info->labelrevout_flag);
          }
          

          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if ( args_info->score_algs_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group score_algs were given. At most one is required.%s\n", CMDLINE_PARSER_PACKAGE, args_info->score_algs_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }
  


  if (check_required)
    {
      if (! args_info->hmmnamefile_given)
        {
          fprintf (stderr, "%s: '--hmmnamefile' ('-m') option required%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
          error = 1;
        }
      if (! args_info->seqnamefile_given)
        {
          fprintf (stderr, "%s: '--seqnamefile' ('-s') option required%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
          error = 1;
        }
      if (! args_info->seqformat_given)
        {
          fprintf (stderr, "%s: '--seqformat' ('-f') option required%s\n", CMDLINE_PARSER_PACKAGE, (additional_error ? additional_error : ""));
          error = 1;
        }
    }

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  return (EXIT_FAILURE);
}
