#
# $Name:  $ - $Id: Makefile.mpi4_sql,v 1.22 2007/12/13 14:38:19 wrp Exp $
#
# 21 July, 2000
#
# Makefile for MPI versions of the parallel library comparison programs.
# this file is derived from Makefile.pvm, with only a few differences:
# (1) -DMPI_SRC instead of -DPVM_SRC
# (2) programs are mp34comp*, ms34comp*, and mu34comp* rather than pv34comp*, etc.
# (3) MPI does not require/allow a "worker" program, thus no c3.work*
#

CC= mpicc -g -O
NCC= mpicc -O
LCC= mpicc -O

#ARCH   =       ALPHAMP  (get from $ARCH)

#MPI_ROOT = /opt/share/mpi
#PLIB    =       -L${MPI_ROOT}/lib -lmpich
#XDIR    =       /seqprg/pvm3/bin/LINUX
XDIR    =       ${HOME}/pvm3/bin/LINUX
SDIR    =       .

CFLAGS= -DMPI_SRC -DUNIX -DPCOMPLIB -DBFR=1200 -I${MPI_ROOT}/include -DSRAND=srand -DRAND=random -DHAS_INTTYPES -DSAMP_STATS -DMYSQL_DB -I/usr/include/mysql -DPGSQL_DB -I/usr/include/pgsql
# -DMYSQL_DB -I/usr/include/mysql
# -DSFCHAR="'|'" -DSUPERFAMNUM 

# standard nxgetaa, no memory mapping for 0 - 6
#LGETLIB=getseq.o lgetlib.o
#NGETLIB=nmgetlib

# memory mapping for 0FASTA, 5PIRVMS, 6GCGBIN
LGETLIB=getseq.o lgetlib.o lgetaa_m.o
NGETLIB=nmgetlib

NRAND=nrandom

SHOWBESTC = mshowbest.c
SHOWALIGN = mshowalign
MWH = p_mw.h
MWHP = p_mw.h w_mw.h

NCBL_LIB=ncbl2_mlib.o mysql_lib.o
#NCBL_LIB=ncbl2_mlib.o
LIB_M= -L/usr/lib/mysql -lmysqlclient -lz -lm -L/usr/lib/pgsql -lpq -lcrypt -lssl
#LIB_M= -lm

LFLAGS= -o

# set up files for SSE2/Altivec acceleration
#
include ../make/Makefile.sse_alt

# no acceleration
#
DROPGSW_O = $(DROPGSW_NA_O)
DROPLAL_O = $(DROPLAL_NA_O)

include ../make/Makefile.mpcom

include ../make/Makefile.fcom

